platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
# plugin 'cocoapods-fix-react-native'

def shared
    pod 'Marshal'
    pod 'KeychainAccess'
    pod 'BonMot'
    pod 'BLEAirQuality', :path => './Submodules/BLEAirQuality'
    pod 'Alamofire'
    pod 'Anchorage'
    pod 'Swiftilities', :git => 'https://github.com/Raizlabs/Swiftilities.git', :branch => 'xcode10_compat'
end

target 'AirQualityDashboard' do
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => './React/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTAnimation',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "./React/node_modules/react-native/ReactCommon/yoga"
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => './React/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => './React/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => './React/node_modules/react-native/third-party-podspecs/Folly.podspec'


  pod 'Instabug'
  pod 'Crashlytics'

  pod 'GoogleAnalytics',   '~>3.0'
  
  pod 'SimulatorStatusMagic', :configurations => ['Debug']

  target 'AirQualityDashboardTests' do
    pod 'OHHTTPStubs/Swift'
  end

  shared()
end

target 'Services' do
    shared()
end

pod 'SwiftGen'
pod 'Sourcery', '~> 0.12.0'
pod 'SwiftLint'

# When using RN in combination with Cocoapods, a lot of 
# things are broken. These are the fixes we had to append 
# to our Podfile when upgrading to ReactNative@0.55.3.
# 
# WARNING: Check those line numbers when you're on a different version!
# https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578
def change_lines_in_file(file_path, &change)
  print "Fixing #{file_path}...\n"

  contents = []

  file = File.open(file_path, 'r')
  file.each_line do | line |
    contents << line
  end
  file.close

  File.open(file_path, 'w') do |f|
    f.puts(change.call(contents))
  end
end

post_install do |installer|
  # https://github.com/facebook/react-native/issues/13198
  change_lines_in_file('./React/node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
    lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
  end

  # https://github.com/facebook/react-native/issues/16039
  change_lines_in_file('./React/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
    lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
  end
end